# Generated by Django 2.2.7 on 2019-11-12 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
